# Generated by Django 2.1.2 on 2018-11-05 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20181024_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsHot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('is_detele', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
        ),
        migrations.AlterModelOptions(
            name='newscomment',
            options={'ordering': ('-id',)},
        ),
    ]
